### PR TITLE
Added interface

### PR DESCRIPTION
**Pull request by jstemerdink**
I have added an interface and use the interface in the plugin and the initialization. This to be able to use the plugin when having other base classes that cannot be changed.

### CODE REVIEW

**Comment by valdisiljuconoks** [comment]
Any chances for merge?

**Comment by defsteph** [comment]
Sorry for not replying, I hadn't seen any notification regarding this.

I'll review as soon as I can, but at a cursory glance, it looks fine.

**Comment by jstemerdink** [comment]
ImageResizer.Plugins.EPiServerBlobReader version "4.1.2", ImageResizer version "4.0.5"
The test project that did not have this behavior has a different version I see now, ImageResizer.Plugins.EPiServerBlobReader version "4.0.3", ImageResizer version "4.0.1". So it might be a change in the BlobReader? In edit mode the image was resized to a square after setting the focal point

**Comment by valdisiljuconoks** [comment]
There has been stuff around Edit mode between 4.0.3 and 4.1.

https://github.com/valdisiljuconoks/ImageResizer.Plugins.EPiServerBlobReader/commit/d1fb6f20adf7a213a3f261c157802c289efc18ec

You can read up whole thread about that issue. Might be related... :(

**Comment by jstemerdink** [comment]
Could be indeed. So I better revert that commit for FocalPoint. I'll do that tomorrow.
When rendering the url's for images on my views I hardly ever use the propertyfor though. ImageResizer only kicking in on non edit url's.

**Comment by jstemerdink** [comment]
Reverted the editmode change. Reverting version to 4.0.3 of the BlobReader stopped the cropping and the messed up coordinates

**Comment by defsteph** [comment]
This is now fixed in release 1.2.0.

I will decline this PR, mainly because of inconsistent code formatting. The concept is solid though.

Arguably, I could've asked you to clean up your code, but then we'd spend time passing non-issues between us. Thank you for your contribution.

I have uploaded the .nupkg file to the EPiServer NuGet Feed, so it will be available from there shortly.

**Comment by jstemerdink** [comment]
Everybody has his own formatting style, so this was probably the fastest way to get the interface :)
Thanks for the interface.

**Pull request closed without merging**
